# @package _global_
training:
  task_name: OpenDogeJoystickFlat
  sim_backend: mujoco
algo:
  num_envs: 1024
  max_iterations: 600
  empirical_normalization: true
  obs_groups:
    actor:
      - actor
  policy:
    init_noise_std: 0.5
  algorithm:
    learning_rate: 3.0e-4
    entropy_coef: 5.0e-3
env:
  commands:
    rel_standing_envs: 0.1
    vel_limit:
      - [-0.8, -0.6, -1.5]
      - [0.8, 0.6, 1.5]
  noise_config:
    level: 1.0
  domain_rand:
    randomize_base_mass: true
    added_mass_range: [-0.6, 0.6]
    random_com: true
    com_offset_x: [-0.03, 0.03]
    randomize_ground_friction: true
    ground_friction_multiplier_range: [0.7, 1.3]
    push_robots: true
    push_interval: 350
    max_force: [0.6, 0.6, 0.4]
reward:
  scales:
    tracking_vx: 1.5
    tracking_vy: 2.3
    tracking_ang_vel: 1.5
    cross_axis_suppression: -0.6
    lin_vel_z: -4.0
    ang_vel_xy: -0.5
    base_height: -200.0
    action_rate: -0.005
    action_smooth: -0.002
    similar_to_default: -0.03
    dof_acc: -0.0000005
    stand_still: -0.5
    zero_command_stillness: 3.0
    torques: -0.005
    energy: -0.0001
    contact: 0.24
    swing_feet_z: 10.0
    feet_air_time: 0.5
    joint_mirror: -0.05
    hip_pos: -0.4
    tracking_vel_linear: -0.4
  tracking_sigma: 0.22
  base_height_target: 0.15
